/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData emotion =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muscle =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
